// Menu registration entries. Included from ShineTextureNodeRegistry.cpp inside GetNodeRegistrations().
SHINE_TEXTURE_NODE_ENTRY(UShineTextureSolidColorNode, "SolidColorLabel", "Solid Color", "SolidColorTooltip", "Adds a constant color node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureTextureInputNode, "TextureInputLabel", "Texture Input", "TextureInputTooltip", "Adds a texture asset source node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureNoiseNode, "NoiseLabel", "Noise", "NoiseTooltip", "Adds a procedural noise source node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureFibers1Node, "Fibers1Label", "Fibers 1", "Fibers1Tooltip", "Adds a simple fiber pattern generator node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTexturePerlinNoiseNode, "PerlinNoiseLabel", "Perlin Noise", "PerlinNoiseTooltip", "Adds a smooth Perlin noise generator node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureUvNode, "UvLabel", "UV", "UvTooltip", "Adds a normalized UV coordinate source node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureScalarConstantNode, "ScalarConstantLabel", "Scalar", "ScalarConstantTooltip", "Adds a scalar constant node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureVector2ConstantNode, "Vector2ConstantLabel", "Vector2", "Vector2ConstantTooltip", "Adds a 2D vector constant node.", Source)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureSwizzle2Node, "Swizzle2Label", "Swizzle 2", "Swizzle2Tooltip", "Extracts two components from an input value.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureAppendVector2Node, "AppendVector2Label", "Append 2", "AppendVector2Tooltip", "Builds a 2D vector from two scalar inputs.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureAppendVector3Node, "AppendVector3Label", "Append 3", "AppendVector3Tooltip", "Builds a 3D vector from three scalar inputs.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureAppendVector4Node, "AppendVector4Label", "Append 4", "AppendVector4Tooltip", "Builds a 4D value from four scalar inputs.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureTransform2DNode, "Transform2DLabel", "Transformation 2D", "Transform2DTooltip", "Adds a 2D image transformation node.", Transform)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureBlendNode, "BlendLabel", "Blend", "BlendTooltip", "Adds a color blending node.", Blend)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureMultiplyNode, "MultiplyLabel", "Multiply", "MultiplyTooltip", "Adds a multiply node for combining colors.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureAddNode, "AddLabel", "Add", "AddTooltip", "Adds two values together.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureSubtractNode, "SubtractLabel", "Subtract", "SubtractTooltip", "Subtracts one value from another.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureDivideNode, "DivideLabel", "Divide", "DivideTooltip", "Divides A by B component-wise.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureMinNode, "MinLabel", "Min", "MinTooltip", "Returns the component-wise minimum of two inputs.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureMaxNode, "MaxLabel", "Max", "MaxTooltip", "Returns the component-wise maximum of two inputs.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureAbsNode, "AbsLabel", "Abs", "AbsTooltip", "Returns the absolute value of each component.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureSqrtNode, "SqrtLabel", "Sqrt", "SqrtTooltip", "Applies square root to each component.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureOneMinusNode, "OneMinusLabel", "One Minus", "OneMinusTooltip", "Computes one minus the input value for each component.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureFloorNode, "FloorLabel", "Floor", "FloorTooltip", "Rounds each component down to the nearest integer.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureFracNode, "FracLabel", "Frac", "FracTooltip", "Keeps only the fractional part of each component.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureClampNode, "ClampLabel", "Clamp", "ClampTooltip", "Adds a clamp node for restricting channel range.", Adjust)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureLevelsNode, "LevelsLabel", "Levels", "LevelsTooltip", "Adds a levels remap node.", Adjust)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureBlurNode, "BlurLabel", "Blur", "BlurTooltip", "Adds a box blur preview node.", Filter)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureNormalBlendNode, "NormalBlendLabel", "Normal Blend", "NormalBlendTooltip", "Adds a normal blending node.", Blend)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureChannelPackNode, "ChannelPackLabel", "Channel Pack", "ChannelPackTooltip", "Adds a channel packing node.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureGreaterNode, "GreaterLabel", "Greater", "GreaterTooltip", "Compares two scalar inputs and outputs a boolean mask.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureLessNode, "LessLabel", "Less", "LessTooltip", "Compares two scalar inputs and outputs a boolean mask.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureEqualNode, "EqualLabel", "Equal", "EqualTooltip", "Tests two scalar inputs for near-equality.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureStepNode, "StepLabel", "Step", "StepTooltip", "Outputs a boolean mask when Value is greater than or equal to Edge.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureToFloatNode, "ToFloatLabel", "到浮点", "ToFloatTooltip", "Converts an integer-style value to a scalar float.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureToIntNode, "ToIntLabel", "到整数", "ToIntTooltip", "Quantizes a numeric input to an integer-style value.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureAndNode, "AndLabel", "And", "AndTooltip", "Outputs true when both boolean inputs are true.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureOrNode, "OrLabel", "Or", "OrTooltip", "Outputs true when either boolean input is true.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureNotNode, "NotLabel", "Not", "NotTooltip", "Outputs the inverse of the boolean input.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureSwizzle4Node, "Swizzle4Label", "Swizzle 4", "Swizzle4Tooltip", "Reorders four components from an input value.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureLerpNode, "LerpLabel", "Lerp", "LerpTooltip", "Linearly interpolates between A and B using Alpha.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureModuloNode, "ModuloLabel", "Modulo", "ModuloTooltip", "Returns the floating-point remainder of A divided by B.", Arithmetic)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureMaskNode, "MaskLabel", "Mask", "MaskTooltip", "Keeps selected components and zeros out the rest.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureBreakOutNode, "BreakOutLabel", "Break Out", "BreakOutTooltip", "Splits the input into X, Y, Z, and W scalar outputs.", Vector)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureSelectNode, "SelectLabel", "Select", "SelectTooltip", "Chooses between two values using a boolean condition.", Logic)
SHINE_TEXTURE_NODE_ENTRY(UShineTexturePreviewNode, "PreviewLabel", "Preview", "PreviewTooltip", "Adds an intermediate preview node.", Preview)
SHINE_TEXTURE_NODE_ENTRY(UShineTextureOutputNode, "OutputLabel", "Output", "OutputTooltip", "Adds a final output preview node.", Preview)
